server {
    listen 80;
    server_name localhost;

    root /var/www/public;
    index index.php index.html;

    # Laravel routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Process PHP scripts
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;                # Container app com PHP-FPM
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Deny access to .ht* files
    location ~ /\.ht {
        deny all;
    }

    # Optional: increase buffer size for large requests
    client_max_body_size 100M;
}
